### PR TITLE
Fixes Issue #143 - Implement Presenter Screen

### PR DESCRIPTION
**Pull request by meingorn**
Implement "presenter" screen. Clicking on the "present" button will open up a new tab mirroring your origin in read-only mode, will transfer any messages that may be on screen.

### CODE REVIEW

**Comment by dlindahl** [comment]
Also, why are there three merge commits with `master` and the fix for #136 in here?

**Comment by meingorn** [comment]
Timer works fine for me, what issue were you experiencing? RE your second point, if you change something in the parent window you need to press the "Open Presentation Window" button to update it, which allows the presenter to go other places on the app without the presenter window being affected. Not sure why those merge commits are showing, squashing didn't help but I can try again - issue popped up on my last PR and you said ignore it.

**Comment by dlindahl** [comment]
1. Open App
2. Click Timer
3. Click "Open Presentation Window"
4. Focus to parent window
5. Click "Up" arrow on minutes
6. Note that Presentation Window display did not change
7. Click "Start"
8. Note that Presentation Window display did not change
9. Allow time to run out and show Alert
10. Note that Presentation Window display did not change

**Comment by meingorn** [comment]
You have to set the time before opening the presentation window/ reopen the presentation window once the time is set. I see how this is not ideal - I'll take a crack at a solution

**Comment by dlindahl** [comment]
> At the least, the main app view should have a UI element that when clicked, spawns a new browser window pointed at a URL that renders the presentation/read-only view. Anytime an Alert or message is displayed or the time changes in the display (either through configuration or running clock tick), that change should be immediately reflected in the second screen.

In case that is still ambiguous, the Presenter window should always mirror exactly what is displayed in the non-Presenter window with the exception of any interactive elements (buttons, UI controls, etc.)

**Pull request merged**
