### PR TITLE
Close #66. Adds Jest code coverage thresholds for build to fail if below

### LINKED ISSUE #66: Add enforcement of code coverage metrics 🎯1/2 day
While code coverage is currently being reported during test runs, the coverage levels are not enforced (meaning if the level drops due to new features without tests, the build does not fail)

In order to increase the quality of the codebase we need to, the build should fail if code coverage drops below whatever the current level is.

### PR DESCRIPTION
**Pull request by kaxcode**

### CODE REVIEW

**Comment by kaxcode** [comment]
@dlindahl not sure what new code to write so I'm just gonna temp delete a test to see if the build fails. What's the benefit of having the config in a jest.config.js file instead of the package.json?

**Comment by kaxcode** [comment]
@dlindahl according to the docs I can only use the coverageThreshold option in a `package.json` file.

**Comment by kaxcode** [comment]
@dlindahl I tried setting this line up in `package.json` "test": "react-scripts test --config ./jest.config.js --coverage --env=jsdom". I set up the `jest.config.js` file up but it kept failing. I can't figure out how you can use a config jest file and have create-react-app read it. https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/scripts/test.js

**Comment by dlindahl** [comment]
Yeah, it looks like [CRA does not support custom config files](https://github.com/facebook/create-react-app/issues/1318). Since we can't change that, its OK to keep it in `package.json`

I prefer keeping the config external because its more explicit. In the event there is an issue with the config, you know exactly where to go. Overloading the `package.json` ends up being a great way to hide things. Additionally, as more and more configs get added to it, its becomes bloated and hard to maintain.

This looks good. Squash your commits and merge away!

**Pull request merged**
